// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6u-yB-nRpgX2nB0FBueWiXpjBnwKFpAw',
    appId: '1:720808567471:web:412fe7a32f6999c3726a5a',
    messagingSenderId: '720808567471',
    projectId: 'diente-c6f11',
    authDomain: 'diente-c6f11.firebaseapp.com',
    storageBucket: 'diente-c6f11.appspot.com',
    measurementId: 'G-JPVBVPZKBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86TD7sEbndIgBsYYDorkR1aDf_I45gRk',
    appId: '1:720808567471:android:ea4f686713f3ee71726a5a',
    messagingSenderId: '720808567471',
    projectId: 'diente-c6f11',
    storageBucket: 'diente-c6f11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFK2LYBEUR6wim8neKW3CNpLE1qD3-So',
    appId: '1:720808567471:ios:98769242a075c998726a5a',
    messagingSenderId: '720808567471',
    projectId: 'diente-c6f11',
    storageBucket: 'diente-c6f11.appspot.com',
    iosBundleId: 'com.example.diente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFK2LYBEUR6wim8neKW3CNpLE1qD3-So',
    appId: '1:720808567471:ios:98769242a075c998726a5a',
    messagingSenderId: '720808567471',
    projectId: 'diente-c6f11',
    storageBucket: 'diente-c6f11.appspot.com',
    iosBundleId: 'com.example.diente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6u-yB-nRpgX2nB0FBueWiXpjBnwKFpAw',
    appId: '1:720808567471:web:36c84b70fbbf3d53726a5a',
    messagingSenderId: '720808567471',
    projectId: 'diente-c6f11',
    authDomain: 'diente-c6f11.firebaseapp.com',
    storageBucket: 'diente-c6f11.appspot.com',
    measurementId: 'G-0BH99E5JSH',
  );
}
