// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFm02uVvwCUWW2IuM_hp0bZOpW_PeQyk',
    appId: '1:312200157189:web:ddee25d3d64febb3ffe46c',
    messagingSenderId: '312200157189',
    projectId: 'diente-e540a',
    authDomain: 'diente-e540a.firebaseapp.com',
    storageBucket: 'diente-e540a.appspot.com',
    measurementId: 'G-2J3L3ENZG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNVyBzYP0Uw8BkpVjtrx1dtxclJ_AT2M',
    appId: '1:312200157189:android:69ac22afcd1cc78fffe46c',
    messagingSenderId: '312200157189',
    projectId: 'diente-e540a',
    storageBucket: 'diente-e540a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARvvnGOujmzvIyZnUZvLcoG0Bbg40704',
    appId: '1:312200157189:ios:cca0c587d4ef2617ffe46c',
    messagingSenderId: '312200157189',
    projectId: 'diente-e540a',
    storageBucket: 'diente-e540a.appspot.com',
    iosBundleId: 'com.example.diente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCARvvnGOujmzvIyZnUZvLcoG0Bbg40704',
    appId: '1:312200157189:ios:cca0c587d4ef2617ffe46c',
    messagingSenderId: '312200157189',
    projectId: 'diente-e540a',
    storageBucket: 'diente-e540a.appspot.com',
    iosBundleId: 'com.example.diente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjFm02uVvwCUWW2IuM_hp0bZOpW_PeQyk',
    appId: '1:312200157189:web:680811c1a4722470ffe46c',
    messagingSenderId: '312200157189',
    projectId: 'diente-e540a',
    authDomain: 'diente-e540a.firebaseapp.com',
    storageBucket: 'diente-e540a.appspot.com',
    measurementId: 'G-FZE0QS5CQH',
  );
}
